AMWP/Models/Members.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMWP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Members
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Members()
        {
            this.Cash = new HashSet<Cash>();
            this.Managements = new HashSet<Managements>();
            this.Properties = new HashSet<Properties>();
            this.SecOrders = new HashSet<SecOrders>();
        }

        [DisplayName("會員代碼")]
        public int MemID { get; set; }

        [DisplayName("會員帳號")]
        [Required(ErrorMessage = "請輸入會員帳號")]
        [EmailAddress(ErrorMessage = "帳號請輸入電子郵件信箱")]        
        public string Account { get; set; }

        string password;
        [DisplayName("密碼")]
        [Required(ErrorMessage = "請填寫密碼")]
        [DataType(DataType.Password)]
        //[MinLength(8, ErrorMessage = "密碼最少8碼")]
        public string Password
        {
            get
            {
                return password;
            }
            set
            {
                password = BusinessRules.getHashPassword(value);
            }
        }

        [DisplayName("會員姓名")]
        [StringLength(50, ErrorMessage = "姓名不可超過50個字")]
        [Required(ErrorMessage = "請填寫會員姓名")]
        public string Name { get; set; }

        [DisplayName("加入日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public System.DateTime CreatedDate { get; set; }

        [DisplayName("帳號狀態")]
        [DefaultValue(true)]
        public bool Status { get; set; }

        [DisplayName("預設幣別")]
        [Required(ErrorMessage = "請輸入預設幣別")]        
        public string CCYID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cash> Cash { get; set; }
        public virtual Currencies Currencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Managements> Managements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Properties> Properties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecOrders> SecOrders { get; set; }
    }
}

AMWP/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AMWP.Models;
using AMWP.ViewModels;
using Microsoft.Ajax.Utilities;

namespace AMWP.Controllers
{
    [LoginCheck(type = 2)]
    public class MembersController : Controller
    {
        private AMWPEntities db = new AMWPEntities();
        SetData sd = new SetData();

        [LoginCheck]
        // GET: Members
        public ActionResult Index()
        {
            var members = db.Members.Include(m => m.Currencies);
            return View(members.ToList());
        }
        [LoginCheck]
        // GET: Members/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Members members = db.Members.Find(id);
            if (members == null)
            {
                return HttpNotFound();
            }
            return View(members);
        }

        [LoginCheck(flag =false)]
        // GET: Members/Create
        public ActionResult Create()
        {
            //ViewBag.CCYID = new SelectList(db.Currencies, "CCYID", "Name");
            ViewBag.CCYID = db.Currencies.ToList();
            return View();
        }

        // POST: Members/Create
        // 若要避免過量張貼攻擊，請啟用您要繫結的特定屬性。
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [LoginCheck(flag = false)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MemID,Account,Password,Name,CreatedDate,Status,CCYID")] Members members)
        {
            Boolean acntExists = db.Members.ToList().Exists(m => m.Account.Equals(members.Account));
            if (acntExists)
            {
                ViewBag.SignUp = "已有會員使用本帳號，請更換帳號！";
                ViewBag.CCYID = db.Currencies.ToList();
                return View(members);
            }
            if (ModelState.IsValid)
            {
                db.Members.Add(members);
                db.SaveChanges();
                TempData["SignUp"] = "註冊成功，請依您的帳號密碼登入本站！";
                return RedirectToAction("Login","MemberLogin");
            }
                ViewBag.CCYID = db.Currencies.ToList();
                return View(members);  
            
        }
        [LoginCheck]
        // GET: Members/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Members members = db.Members.Find(id);
            if (members == null)
            {
                return HttpNotFound();
            }
            ViewBag.CCYID = new SelectList(db.Currencies, "CCYID", "Name", members.CCYID);
            return View(members);
        }

        // POST: Members/Edit/5
        // 若要避免過量張貼攻擊，請啟用您要繫結的特定屬性。
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [LoginCheck]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MemID,Account,Password,Name,CreatedDate,Status,CCYID")] Members members)
        {
            if (ModelState.IsValid)
            {
                db.Entry(members).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CCYID = new SelectList(db.Currencies, "CCYID", "Name", members.CCYID);
            return RedirectToAction("Index");
        }

        public ActionResult MemberEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Members members = db.Members.Find(id);
            if (members == null)
            {
                return HttpNotFound();
            }
            ViewBag.CCYID = new SelectList(db.Currencies, "CCYID", "Name", members.CCYID);
            return View(members);
        }

        // POST: Members/Edit/5
        // 若要避免過量張貼攻擊，請啟用您要繫結的特定屬性。
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult MemberEdit([Bind(Include = "MemID,Account,Password,Name,CreatedDate,Status,CCYID")] Members members)
        {
            if (ModelState.IsValid)
            {
                db.Entry(members).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CCYID = new SelectList(db.Currencies, "CCYID", "Name", members.CCYID);
            return View(members);
        }
        [LoginCheck]
        // GET: Members/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Members members = db.Members.Find(id);
            if (members == null)
            {
                return HttpNotFound();
            }
            db.Members.Remove(members);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [LoginCheck]
        public ActionResult ChangeStatus(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var member = db.Members.Find(id);
            if (member != null)
            {
                string sql = "";
                if (member.Status)
                {
                    sql = "update Members set [Status] = 'false' where MemID = @id";
                }
                else
                {
                    sql = "update Members set [Status] = 'true' where MemID = @id";
                }  
                List<SqlParameter> list = new List<SqlParameter> { new SqlParameter("id", id) };
                sd.executeSql(sql,list);
                TempData["Status"] = Convert.ToString(member.Account) + "會員狀態改變！";
            }
            else
            {
                return HttpNotFound();
            }
            return RedirectToAction("Index"); 
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AMWP/Views/Members/Create.cshtml
@model AMWP.Models.Members

@{
    ViewBag.Title = "註冊會員";
    Layout = "~/Views/Shared/_MemberLayout.cshtml";
    var usd = "USD";
}
<hr />
<h3 class="alert alert-info text-center">註冊會員</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form">
    <div class="form-group row align-items-baseline">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="col-md-5 text-md-right">
            @Html.LabelFor(model => model.Account, htmlAttributes: new { @class = "control-label" })
        </div>
        <div class="col-md-7">
            @Html.EditorFor(model => model.Account, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Account, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row align-items-baseline">
        <div class="col-md-5 text-md-right">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label" })
        </div>
        <div class="col-md-7">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row align-items-baseline">
        <div class="col-md-5 text-md-right">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
        </div>
        <div class="col-md-7">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group row align-items-baseline" hidden>
        <div class="col-md-5 text-md-right ">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label" })
        </div>
        <div class="col-md-7">
            <input id="CreatedDate" name="CreatedDate" type="date" class="form-control" value="2023-01-01" />
            @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group row align-items-baseline" hidden>
        <div class="col-md-5 text-md-right">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label" })
        </div>
        <div class="col-md-7">
            <div class="checkbox">
                <input id="Status" name="Status" type="checkbox" value="true" checked />
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-group row align-items-baseline">
        <div class="col-md-5 text-md-right ">
            @Html.LabelFor(model => model.CCYID, "預設幣別", htmlAttributes: new { @class = "control-label" })
        </div>
        <div class="col-md-7">
            <select id="CCYID" name="CCYID" class="form-control">
                @foreach (var item in ViewBag.CCYID)
                {
                    <option value="@item.CCYID" @(item.CCYID == usd ? "selected" : "")>@item.Name</option>
                }
            </select>
            @Html.ValidationMessageFor(model => model.CCYID, "", new { @class = "text-danger" })
        </div>
    </div>
        <h5 class="text-danger text-center">@ViewBag.SignUp</h5>
    <div class="form-group">
        <div class="col-md-8 text-right">
            <input type="submit" value="註冊會員" class="btn btn-success" onclick="getToday()" />
    @Html.ActionLink("已是會員？", "Login", "MemberLogin", null, new { @class = "btn btn-link" })
        </div>
    </div>
    </div>
}
    @section CSS{
        <style>
            .alert-info {
                color: #0c5460;
                background-color: #c9f8ed;
                border-color: #bee5eb;
            }
        </style>
    }


    @section scripts {
        @Scripts.Render("~/bundles/jqueryval")
        <script src="~/Scripts/moment.min.js"></script>
        <script>
            var today = moment().format('YYYY-MM-DD');
            function getToday() {
                document.getElementById("CreatedDate").defaultValue = today;
            }
        </script>

    }

AMWP/Views/Members/Delete.cshtml
@model AMWP.Models.Members

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Members</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Account)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Account)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Currencies.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Currencies.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AMWP/Views/Members/Details.cshtml
@model AMWP.Models.Members

@{
    ViewBag.Title = "會員資料管理";
    Layout = "~/Views/Shared/_MemberLayout.cshtml";
}

<h3 class="alert alert-info text-center">會員資料</h3>


    <div class="container">
        <div class="form-group row align-items-baseline">
            <div class="col-md-5 text-md-right">
                @Html.DisplayNameFor(model => model.Account)
            </div>
            <div class="col-md-7">
                @Html.DisplayFor(model => model.Account)
            </div>
        </div>
        

        <div>
            @Html.DisplayNameFor(model => model.Name)
        </div>

        <div>
            @Html.DisplayFor(model => model.Name)
        </div>

        <div>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </div>

        <div>
            @Html.DisplayFor(model => model.CreatedDate)
        </div>

        <div>
            @Html.DisplayNameFor(model => model.Status)
        </div>

        <div>
            @Html.DisplayFor(model => model.Status)
        </div>

        <div>
            @Html.DisplayNameFor(model => model.Currencies.Name)
        </div>

        <div>
            @Html.DisplayFor(model => model.Currencies.Name)
        </div>

    </div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MemID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

@section CSS{
    <style>
        .alert-info {
            color: #0c5460;
            background-color: #acf2d4;
            border-color: #bee5eb;
        }
    </style>
}

AMWP/Views/Members/Edit.cshtml
@model AMWP.Models.Members

@{
    ViewBag.Title = "會員資料管理";
   

}

    <hr />
<h3 class="alert alert-info text-center">會員資料管理</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="container form">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MemID)

    <div class="form-group row align-items-baseline">
        <div class="col-md-5 text-md-right">
            @Html.LabelFor(model => model.Account, htmlAttributes: new { @class = "control-label" })
        </div>
        <div class="col-md-7">
            @Html.EditorFor(model => model.Account, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Account, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" hidden>
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group row align-items-baseline">
        <div class="col-md-5 text-md-right">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
        </div>
        <div class="col-md-7">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row align-items-baseline">
        <div class="col-md-5 text-md-right">
            @Html.LabelFor(model => model.CCYID, "預設貨幣", htmlAttributes: new { @class = "control-label" })
        </div>
        <div class="col-md-7">
            @Html.DropDownList("CCYID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CCYID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row align-items-baseline">
        <div class="col-md-5 text-md-right">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label" })
        </div>
        <div class="col-md-7">
            @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" hidden>
        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Status)
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-8 text-right">
            <input type="submit" value="確定修改" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("返回會員列表", "Index", null, new { @class = "btn btn-info" })
</div>
@section CSS{
    <style>
        .alert-info {
            color: #0c5460;
            background-color: #acf2d4;
            border-color: #bee5eb;
        }
    </style>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AMWP/Views/Members/Index.cshtml
@model IEnumerable<AMWP.Models.Members>

@{
    ViewBag.Title = "會員管理";
}
<hr />
<h3 class="alert alert-info text-center">會員列表</h3>

<div class="row">
    <h4 class="col-md-8 text-right text-danger" id="msg">@TempData["Status"]</h4>
    @*<div class="col-md-4 text-right mb-3">
        @Html.ActionLink("新增會員", "Create", null, new { @class = "btn btn-primary" })
    </div>*@
</div>
<table class="table table-striped table-hover text-center">
    <thead class="thead-dark">

        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MemID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Account)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CCYID)
            </th>
            <th>資料管理</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MemID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Account)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedDate)
                </td>
                <td>
                    <span class="text-@(item.Status? "success":"danger")">@(item.Status? "正常":"封鎖")</span>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Currencies.Name)
                </td>
                <td>
                    @Html.ActionLink("修改", "Edit", new { id = item.MemID }, new { @class = "btn btn-warning" })
                    @Html.ActionLink("帳號管理", "Index", "Managements", new { id = item.MemID }, new { @class = "btn btn-info" })
                    @*@Html.ActionLink("刪除", "Delete", "Members", new { id = item.MemID }, new { @class = "btn btn-danger" })*@
                    <a class="btn btn-@(item.Status? "danger":"success")" href="@Url.Action("ChangeStatus", "Members", new { id = item.MemID })">@(item.Status? "封鎖":"解鎖")</a>


                </td>
            </tr>
        }
    </tbody>
</table>


@section CSS{
    <style>
        .alert-info {
            color: #0c5460;
            background-color: #acf2d4;
            border-color: #bee5eb;
        }
    </style>
}
@section scripts{
    <script>
        $('#navbar .nav-item').removeClass('active');
        $('#navItem2').addClass('active');

        $(document).click(function () {
            $('#msg').hide();
        });
       

    </script>
   
}

AMWP/Views/Members/MemberEdit.cshtml
@model AMWP.Models.Members

@{
    ViewBag.Title = "會員資料管理";
    Layout = "~/Views/Shared/_MemberLayout.cshtml";

}

<h3 class="alert alert-info text-center">會員資料管理</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container form">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MemID)

        <div class="form-group row align-items-baseline">
            <div class="col-md-5 text-md-right">
                @Html.LabelFor(model => model.Account, htmlAttributes: new { @class = "control-label" })
            </div>
            <div class="col-md-7">
                @Html.EditorFor(model => model.Account, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Account, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group" hidden>
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row align-items-baseline">
            <div class="col-md-5 text-md-right">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
            </div>
            <div class="col-md-7">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row align-items-baseline">
            <div class="col-md-5 text-md-right">
                @Html.LabelFor(model => model.CCYID, "預設貨幣", htmlAttributes: new { @class = "control-label" })
            </div>
            <div class="col-md-7">
                @Html.DropDownList("CCYID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CCYID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row align-items-baseline">
            <div class="col-md-5 text-md-right">
                @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label" })
            </div>
            <div class="col-md-7">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group" hidden>
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-8 text-right">
                <input type="submit" value="確定修改" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@*<div>
        @Html.ActionLink("返回會員列表", "Index", null, new { @class = "btn btn-info" })
    </div>*@
@section CSS{
    <style>
        .alert-info {
            color: #0c5460;
            background-color: #acf2d4;
            border-color: #bee5eb;
        }
    </style>
}
@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script>
    $('#sidebarMenu .nav-link').removeClass('active');
    $('#navLink9').addClass('active');
    </script>
}